name: euro_mobile
description: Aplicação mobile arcen

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^3.0.1
  flutter_lints: ^2.0.1
  flutter_svg: ^1.1.1+1
  flutter_translate: ^4.0.3
  flutter_translate_annotations: ^2.1.0
  flutter_secure_storage: ^5.0.2
  lottie: ^1.4.0
  scrollable_positioned_list: ^0.3.2
  fl_chart: ^0.55.0
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  open_file: ^3.2.1
  syncfusion_flutter_charts: ^20.2.40
  syncfusion_flutter_datepicker: ^20.2.40
  syncfusion_flutter_gauges: ^20.2.40
  font_awesome_flutter: ^10.1.0
  flutter_carousel_slider: ^1.0.9
  flutter_animation_progress_bar: ^2.2.1
  timeline_tile: ^2.0.0
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/arcen.png
    - assets/images/logo_arcen.svg
    - assets/images/launch_image.png
    - assets/images/truck.png
    - assets/images/pump.png
    - assets/images/pile-concrete.png
    - assets/images/concrete-truck.png
    - assets/images/lotties/search.json
    - assets/images/lotties/notfound.json
    - assets/i18n/
    - assets/flag/pt.svg
    - assets/flag/gb.svg
    - assets/flag/fr.svg
    - assets/flag/es.svg
    - assets/ca/
